# Task Analysis {.appendix}

#### Task Prerequisites

Given that this is a user guide for calculating statistical metrics, FAR and RR, and interpreting them, the only prerequisites are knowledge ones as we will not be applying these concepts to any code. The knowledge prerequisites are:

-   Understanding of basic probabilities: p = P(X \> u), where X is a random variable and u is a threshold value. Additionally, an understanding of probability distribution functions needed.

-   An interest in the logic/reasoning of "necessary" vs. "sufficient" causation.

-   Basic knowledge of climate risk issues and themes of recent scientific findings in the last 20 years related to human effects on climate change.

#### Data Requirements

-   The data must represent the same random variable (X) measured under two different scenarios: the factual and counterfacutal.

-   The data is generally assumed to be real numbers, but the range matters significantly based on the event being analyzed. For example, if analyzing an extreme precipitation event, data should always be positive whereas temperature data can be positive or negative.

-   Distribution assumptions: the data can be normally distributed but it does not have to be. In fact, when studying the attribution of causal factors for rare events, Extreme Value Theory (EVT) distributions are preferred because they are better for data with heavy tails.

#### Outline of Task Steps

1.  Define the Event and Threshold (u)
2.  Define the Factual and Counterfactual Scenarios
    1.  Choose a method for probability estimation
3.  Calculate FAR and RR
4.  Apply calculated metrics to Theoretical Causal Framework
    a.  Probability of Necessary Causation
    b.  Probability of Sufficient Causation
5.  Visualize and Communicate Shift in Probability Density Functions
    1.  Provide example plots
    2.  Explain interpretation and communication for stakeholders

#### On-the-fly Decisions

-   Threshold Decision (u): user must decide where to set the threshold for the event of interest. The threshold sets the benchmark/definition for what makes an event "rare".

-   Distribution Model Choice: user must evaluate which type of distribution is best for their data. This will often vary based on the event type (e.g. rainfall)

-   Spatiotemporal Scaling: user must decide how to define the event in terms of time and space/geography. For example, for a climate event, should the event be defined by a single day at one station, or a three-month over an entire continent.

#### Task Follow-up Questions

-   Is the chosen threshold high anough to represent a truly extreme event without making confidence intervals too wide?

    -   Adjustment: if the sample size above u is too small, the user might need to use Extreme Value Theory.

-   Is the statistical model appropriate? (e.g. Did I assume a normal distribution for a variable that actually has heavy tails?)

    -   Adjustment: choose a statistical model that more honestly represents the data

#### Product Evaluation Criteria

-   Can the user complete the calculations?

-   Do the calculated FAR and RR align with the visual shifts in the density plots?

-   Was an honest distribution model used to represent the data so risk could be accurately estimated?

-   Is the chosen threshold (u) high enought to be considered "extreme" while maintaining useful confidence intervals?

-   Can the user accurately interpret metrics and communicate visualizations to stakeholders? Can stakeholders understand the communication and make decisions?

-   Does the final conclusion correctly distinguish between the cause being necessary (the event wouldn't have happened without it) versus sufficient (the cause alone triggers the event)?

## Additional Guidance

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic).

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. This document should remain as an appendix to your main report.
