# Topic

For my user guide, I'm going to provide a tutorial on calculating and communicating Fraction of Attributable Risk (FAR) and Risk Ratio (RR). These metrics are fundamental parts of Extreme Event Attribution (EEA). EEA aims to evalutate how anthropogenic forcings, like increased atmospheric greenhouse gases, affect the likelihood of specific extreme climate events. Along with calculations, the tutorial will include how these metrics can be used to visualize the shift in event probability between the factual and counterfactual world. Additionally, the tutorial will explain the significance of FAR and RR in climate science and how these metrics and visuals may be used to communicate the causality of human behaviors on the climate to decision-making stakeholders. 



::: callout-note
# Comments/suggestions

Ok. Make sure you connect them appropriately to the climate risk issue, and you may want to also look at different ways to visualize climate risk - Lace Padilla has some good stuff on that. 

:::
